// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxES72i9KYJmVjUT2Hqxn7nfU1PwanJ6w',
    appId: '1:763168808348:web:2e171ae608c02a01387c59',
    messagingSenderId: '763168808348',
    projectId: 'findsoccermatchesapp',
    authDomain: 'findsoccermatchesapp.firebaseapp.com',
    storageBucket: 'findsoccermatchesapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZO8gLOxh9W_mflrffrN2w-BGEpZMD6g',
    appId: '1:763168808348:android:1b2582d61a40b37c387c59',
    messagingSenderId: '763168808348',
    projectId: 'findsoccermatchesapp',
    storageBucket: 'findsoccermatchesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJGr0sGdV1H6ef4Q1yddRoYrHt6U0hQt8',
    appId: '1:763168808348:ios:3cb6b4bcc46e16ce387c59',
    messagingSenderId: '763168808348',
    projectId: 'findsoccermatchesapp',
    storageBucket: 'findsoccermatchesapp.appspot.com',
    iosClientId:
        '763168808348-u0u0fs4svmto3pfqrnshj54kbq9ai75b.apps.googleusercontent.com',
    iosBundleId: 'tim.soccer.finder.soccerFinder',
  );
}
